### ISSUE TITLE
Exafmm_t.h Error

### ISSUE THREAD

**Issue by Reed-in-the-wind** [exafmm/exafmm-t#20]
Hi. I came across an error when installing the exafmm-t on my server (ARMV8, CenOS). But after configuration and make, the following error messages appears. Is there anyone who has the similar problem? I am wondering whether it is just because the exafmm does not support ARMV8 architecture very well. 

" 
../include/exafmm_t.h:60:21: error: ‘SIMD_BYTES’ was not declared in this scope
   const int NSIMD = SIMD_BYTES / int(sizeof(real_t));  //!< SIMD vector length (SIMD_BYTES defined in vec.h)

../include/laplace.h:40:60: error: expression list treated as compound expression in initializer [-fpermissive]
         simdvec tx(&trg_coord[3*t+0], 3*(int)sizeof(real_t));
"

**Comment by tingyu66** [comment]
Hello, exafmm-t does not support ARM architecture for now, and it has been only tested on x86 processors.
